MPI_MAX_RECEIVE_REQUESTS: 5000
MPI_MAX_SEND_REQUESTS: 5000
MPI_RECEIVE_NUM: 4
accumulator_node_id: 0
block_per_line: 2000
communicator_buffer_size: 6485760
communicator_thread_num: 4
disc_lambda_l2: 5
disc_method: MAX_GAIN
disc_model_output_file: /user/jiyin/disc1
disc_operation: TRAIN
disc_sample_num: -1
early_stop_threshold: 5
enable_early_stop: true
enable_fully_corrective: true
enable_importance_sample: false
eval_frequency: 1
evaluate_output_file: ./auc.out
feat_info_file: ''
gbdt_model_output_file: /user/jiyin/model11
gbdt_operation: TRAIN
hdfs_defaultRetryNum: 1
hdfs_fsName: hdfs://emr-header-1:9000
hdfs_fsUgi: hadoop,1000
importance_sample_pattern: 0
importance_sample_rate: 0.5
is_sampling_data: false
lambda_l1: 1.9584429413591948
lambda_l2: 1.4658877347286814
local_shard_num: 20
loss_type: LS
max_bucket_num: 50
max_feat_num: 9999999999
max_leaf_num: 100
max_tree_depth: 5
min_bucket_weight: 5
min_feat_occur_threshold: 10
min_node_weight: 300
momentum: 0.6894034921707649
neg_data_sample_count: 1572454
output_dir: ''
pclient_thread_num: 4
pos_data_sample_count: 27547
pos_weight: 1
positive_threshold: 0.5
predict_output_file: /user/jiyin/predict1
read_thread_num: 1
retry_num: 1
step_size: 0.05
test_data_file: /user/jiyin/test
thread_num: 0
train_data_file: /user/jiyin/20170913/train2
tree_iteration_times: 10
tree_num: 10
tree_type: type1
write_thread_num: 1
